---
name: TeamCity Config Test

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/teamcity-test.yaml'
      - '!.teamcity/components/generated/**'
      - '!.teamcity/target/**'
      - '.teamcity/**'

concurrency:
  group: 'tctest-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  teamcity-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: zulu
          java-version: 17
          java-package: jdk
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: make teamcity-test
